bootstrap_servers: localhost:9092
dataset_uri: /tmp/census_data/adult.data
time_interval: 100
census_input_preprocess_topic: census_input_preprocess_topic
census_input_topic: census_input_topic
census_output_topic: census_output_topic